name: Build and publish svg artifacts

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - name: Install dependencies
        run: yarn --immutable
      - name: Fetch icon sources
        run: cd packages/react-icons && yarn fetch
      - name: Build icons
        run: cd packages/react-icons && yarn build-svgs
      - uses: actions/upload-artifact@v3
        with:
          name: react-icons-svgs
          path: packages/_react-icons_all-svgs/
