name: Build and publish svg artifacts

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - name: Install dependencies
        run: yarn --immutable
      - name: Fetch icon sources
        run: cd packages/react-icons && yarn fetch
      - name: Build icons
        run: cd packages/react-icons && yarn build-svgs
      - name: create svgs icon tarball
        run: tar cvzf react-icons-svgs.tar.gz -C packages/_react-icons_all-svgs .
      - name: create xmls icon tarball
        run: tar cvzf react-icons-xmls.tar.gz -C packages/_react-icons_all-xmls .
      - uses: actions/upload-artifact@v3
        with:
          name: react-icons-svgs
          path: react-icons-svgs.tar.gz
      - uses: actions/upload-artifact@v3
        with:
          name: react-icons-xmls
          path: react-icons-xmls.tar.gz
