name: Node.js CI

"on":
  - push
  - pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - name: corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn --immutable
      - name: Formatter
        run: yarn format:ci
      - name: Lint
        run: yarn lint
      - name: Build Packages
        run: BASE_PATH=/react-icons ./build-script.sh
      - uses: actions/upload-artifact@v3
        with:
          path: packages/_react-icons_*/*.tgz
